### ISSUE TITLE
App crashed on multiple scroll continoulsy

### ISSUE THREAD

**Issue by vivekverma1993** [iltercengiz/ICViewPager#67]
I am getting an error on continued scroll between tabs. I have limited the tab count to 3.
The error is :  Assertion failure in -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:], *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [views count] == 3

Please help

**Comment by alexhong39** [comment]
Hello, Everybody.

I fixed this issue.
It is a great pager.

Thank you Ilter and thanks ICViewPager!

**Comment by ReddyBashaShaik** [comment]
@alexhong39 Hi,
Can you please tell me where I have to make change to fix above issue? or will you provide me the link for code.

Thanks

**Comment by alexhong39** [comment]
Please have a test like as the followings:

###### 1 Replace

In `- (void)setActiveContentIndex:(NSUInteger)activeContentIndex` method

replace the codes in `if (activeContentIndex == self.activeContentIndex)` case statement as like it

```
if (activeContentIndex == self.activeContentIndex) {

        self.animatingToTab = NO;

}
```

###### 2 Insert

In `- (void)defaultSetup` method
under the this codes

```
    // Select starting tab
    NSUInteger index = [self.startFromSecondTab boolValue] ? 1 : 0;
```

insert the followings

```
    UIViewController *viewController = [self viewControllerAtIndex:index];

    if (!viewController) {
        viewController = [[UIViewController alloc] init];
        viewController.view = [[UIView alloc] init];
        viewController.view.backgroundColor = [UIColor clearColor];
    }

    [self.pageViewController setViewControllers:@[viewController]
                                      direction:UIPageViewControllerNavigationDirectionForward
                                       animated:NO
                                     completion:nil];
```

Enjoy!

Thank you.
Alex.

**Comment by Saulenco** [comment]
Just added @alexhong39  answer and i can still reproduce the crash :(. It is very simple to reproduce , wile swiping tab on tab.

**Comment by Saulenco** [comment]
And also there is other problem with multiple touch on the tabs, i solve it with button in place of gesture recogniser , and add setExclusiveTouch:YES to buttons, maybe it will help someone :)

**Comment by mikekhristo** [comment]
Try wrapping setViewControllers in dispatch_async as identified here:
http://stackoverflow.com/questions/24000712/pageviewcontroller-setviewcontrollers-crashes-with-invalid-parameter-not-satisf

**Comment by seyfeddin** [comment]
@Saulenco I think @mikekhristo's answer would solve the crashes. Closing this for now.
